[workspace]
members = [
  "crates/include-utils",
  "crates/include-utils-macro",
  "examples/crate",
  "examples/workspace",
]
resolver = "3"

[workspace.package]
version = "0.2.7"
documentation = "https://docs.rs/include-utils"
edition = "2024"
repository = "https://github.com/alekseysidorov/include-utils"
license = "MIT OR Apache-2.0"
rust-version = "1.92"

[workspace.metadata.crane]
name = "include-utils"

[workspace.dependencies]
include-utils = { path = "crates/include-utils", version = "0.2.7", default-features = false }
include-utils-macro = { path = "crates/include-utils-macro", version = "0.2.7" }

cargo_metadata = "0.23.1"
itertools = "0.15.0"
pretty_assertions = "1.4.1"
quote = "1.0.47"
syn = "3.0.6"
manyhow = "0.14.0"
proc-macro2 = "1.0.107"

[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
unsafe_code = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
