[package]
name = "include-utils-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
pretty_assertions = { workspace = true }
itertools = { workspace = true }
