[package]
name = "include-utils-macro"
version.workspace = true
edition.workspace = true
description = "Internal proc macro for the `include-utils` crate."

documentation.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[features]
default = []
workspace = ["dep:cargo_metadata"]

[dependencies]
cargo_metadata = { workspace = true, optional = true }
itertools.workspace = true
manyhow.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
